title: "Interview Docs"
remote_theme: pmarsceill/just-the-docs
# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil



theme: just-the-docs


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 2


# Maximum amount of previews per search result
# Default: 3
search.previews: 3

# Maximum amount of words to display before a matched word in the preview
# Default: 5
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
search.preview_words_after: 10

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true



