title: "Interview Docs"
description: Interview questions and answers notes or docs
baseurl: "/interview-docs" # the subpath of your site, e.g. /blog
url: "https://github.com/sunilsoni" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/",".idea/", "README.md", "Rakefile"
  , "docs/tests/"
]



remote_theme: pmarsceill/just-the-docs
# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

search_enabled: false

theme: jekyll-theme-minimal



# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 2

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_insensitive # Capital letters sorted before lowercase
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Interview questions and answers":
    - "//github.com/sunilsoni/interview-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022-2023 Interview Docs Email: docs.interview@gmail.com"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html