title: Interview Docs
tagline : Interview questions and answers
description: Interview questions and answers notes or docs
# baseurl: "/interview-docs" # the subpath of your site, e.g. /blog
baseurl: ""
url: https://interview-docs.com # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Sunil Soni
  email: docs.interview@gmail.com
  github: sunilsoni

production_url: https://interview-docs.com

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/utils/job-logo.jpeg"

remote_theme: pmarsceill/just-the-docs
# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

theme: jekyll-theme-minimal

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 6

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_insensitive # Capital letters sorted before lowercase
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 6
  # Maximum amount of previews per search result
  # Default: 3
  previews: 10
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 20
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Interview questions and answers":
    - "//github.com/sunilsoni/interview-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022-2023 Interview Docs Email: docs.interview@gmail.com"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-2709176-22
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag


category-list: [System Design,  GraphQL,Array,Data Structures,Dynamic Programming,Intergers,Linked List,Queue,Sorting,String,Angular,Angular Component,Angular Data Binding,Angular Directive,Angular Lazy Loading,Angular Lifecycle Hooks,Angular Pipes,Angular Routing and Navigation,Angular Services,Versioning and releases,RxJS,Amazon Web Services (AWS),AWS CloudFormation,AWS DynamoDB,AWS - Elastic Compute Cloud (EC2),AWS Lambda,Simple Storage Service (S3),Database,Hibernate,MongoDB,Behavioral Design Pattern,Creational Design Pattern,Design Patterns,Structural Design Pattern,DevOps,Docker,Linux,Maven,Collection Framework,Java,Java 8,Java Basics,Multi threading,Kafka,API Gateway,Microservices,Security in Microservices,Managing transactions,Behavioral & Situational,Cucumber,Good Practices,HTTP methods overview,Miscellaneous,Common Java Vulnerabilities,Object-oriented programming(OOPS),React,Spring,Spring AOP,Spring Batch,Spring Boot,Spring MVC,Swagger,Spring Data JPA,Spring Cloud,Spring Security, SQL Queries]